company_name: dev

#zabbix:
#  - integration_name: "zabbix_test"
#    url: "http://127.0.0.1"
#    user: "admin"
#    password: "admin"

#icinga:
#  - integration_name: "icinga_test"
#    url: "http://127.0.0.1"
#    user: "admin"
#    password: "admin"

