# Global Settings
company_name: dev

# Test configuration for Zabbix system
zabbix:
#  - integration_name: "zabbix_test"
#    url: "http://127.0.0.1"
#    user: "admin"
#    password: "admin"

# Test configuration for Icinga system
icinga:
#  - integration_name: "icinga_test"
#    url: "http://127.0.0.1"
#    user: "admin"
#    password: "admin"

