version: '2.1'

services:
  harp-agent:
    image: 'theharpia/harp-agent:v1.0.1'
    volumes:
      - './config.yaml:/code/config.yaml:ro'
    environment:
      - NOTIFICATIONS_SCRAPE_INTERVAL_SECONDS=5
      - GATE_HOST=http://127.0.0.1:8081/api/v1/gate-collector
    restart: on-failure