version: '2.1'

services:
  harp-agent:
    image: 'theharpia/harp-agent:v1.0.2'
    volumes:
      - './config.yaml:/code/config.yaml:ro'
    environment:
      - NOTIFICATIONS_SCRAPE_INTERVAL_SECONDS=5
      - GATE_HOST=http://gate-collector.dev.harpia.io/api/v1/gate-collector
    restart: on-failure