version: '2.1'
services:
  harp-agent:
    image: 'theharpia/harp-agent:v1.0.3'
    volumes:
      - './config.yaml:/code/config.yaml:ro'
    environment:
      - NOTIFICATIONS_SCRAPE_INTERVAL_SECONDS=5
      - LOKI_SERVER=loki-prod.harpia.io
      - LOKI_PORT=443
      - SERVICE_NAME=harp-agent
      - PATH_TO_MS_CONFIG=/code/config.yaml
    restart: on-failure